lsi: false
safe: true
source: https://github.com/0xSkla3/pentesting-notes
theme: jekyll-shell-theme
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
